plugins {
    id 'groovy-gradle-plugin'
    id 'com.gradle.plugin-publish' version '2.2.1'
    id 'maven-publish'
}

group = 'io.github.freehij'
version = '1.0.0-' + (System.getenv("GITHUB_RUN_NUMBER") ?: "dev")

gradlePlugin {
    plugins {
        mcartifact {
            id = 'io.github.freehij.mcartifact'
            displayName = 'Minecraft Artifacts Downloader'
            description = 'Downloads Minecraft artifacts based on version and environment'
            implementationClass = 'io.github.freehij.mcartifact.McArtifactPlugin'
            tags = ['minecraft', 'artifact', 'download']
        }
    }
}

publishing {
    repositories {
        maven {
            name = "github_packages"
            url = uri("https://maven.pkg.github.com/freehij/mcartifact")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
